// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module decision_function_75 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_V_address0,
        x_V_ce0,
        x_V_q0,
        x_V_address1,
        x_V_ce1,
        x_V_q1,
        ap_return
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] x_V_address0;
output   x_V_ce0;
input  [11:0] x_V_q0;
output  [3:0] x_V_address1;
output   x_V_ce1;
input  [11:0] x_V_q1;
output  [11:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] ap_return;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [11:0] scores_reg_449;
wire    ap_CS_fsm_state2;
wire    grp_tree_scores_fu_44_ap_ready;
wire    grp_tree_scores_fu_44_ap_done;
reg   [11:0] scores_1_reg_454;
reg   [11:0] scores_2_reg_459;
reg   [11:0] scores_3_reg_464;
reg   [11:0] scores_4_reg_469;
reg   [11:0] scores_5_reg_474;
reg   [11:0] scores_6_reg_479;
reg   [11:0] scores_7_reg_484;
reg   [11:0] scores_8_reg_489;
reg   [11:0] scores_9_reg_494;
reg   [11:0] scores_s_reg_499;
reg   [11:0] scores_10_reg_504;
reg   [11:0] scores_11_reg_509;
reg   [11:0] scores_12_reg_514;
reg   [11:0] scores_13_reg_519;
reg   [11:0] scores_14_reg_524;
reg   [11:0] scores_15_reg_529;
reg   [11:0] scores_16_reg_534;
reg   [11:0] scores_17_reg_539;
reg   [11:0] scores_18_reg_544;
reg   [11:0] scores_19_reg_549;
reg   [11:0] scores_20_reg_554;
reg   [11:0] scores_21_reg_559;
reg   [11:0] scores_22_reg_564;
reg   [11:0] scores_23_reg_569;
reg   [11:0] scores_24_reg_574;
reg   [11:0] scores_25_reg_579;
reg   [11:0] scores_26_reg_584;
reg   [11:0] scores_27_reg_589;
reg   [11:0] scores_28_reg_594;
reg   [11:0] scores_29_reg_599;
reg   [11:0] scores_30_reg_604;
reg   [11:0] scores_31_reg_609;
reg   [11:0] scores_32_reg_614;
reg   [11:0] scores_33_reg_619;
reg   [11:0] scores_34_reg_624;
reg   [11:0] scores_35_reg_629;
reg   [11:0] scores_36_reg_634;
reg   [11:0] scores_37_reg_639;
reg   [11:0] scores_38_reg_644;
reg   [11:0] scores_39_reg_649;
reg   [11:0] scores_40_reg_654;
reg   [11:0] scores_41_reg_659;
reg   [11:0] scores_42_reg_664;
reg   [11:0] scores_43_reg_669;
reg   [11:0] scores_44_reg_674;
reg   [11:0] scores_45_reg_679;
reg   [11:0] scores_46_reg_684;
reg   [11:0] scores_47_reg_689;
reg   [11:0] scores_48_reg_694;
reg   [11:0] scores_49_reg_699;
reg   [11:0] scores_50_reg_704;
reg   [11:0] scores_51_reg_709;
reg   [11:0] scores_52_reg_714;
reg   [11:0] scores_53_reg_719;
reg   [11:0] scores_54_reg_724;
reg   [11:0] scores_55_reg_729;
reg   [11:0] scores_56_reg_734;
reg   [11:0] scores_57_reg_739;
reg   [11:0] scores_58_reg_744;
reg   [11:0] scores_59_reg_749;
reg   [11:0] scores_60_reg_754;
reg   [11:0] scores_61_reg_759;
reg   [11:0] scores_62_reg_764;
reg   [11:0] scores_63_reg_769;
reg   [11:0] scores_64_reg_774;
reg   [11:0] scores_65_reg_779;
reg   [11:0] scores_66_reg_784;
reg   [11:0] scores_67_reg_789;
reg   [11:0] scores_68_reg_794;
reg   [11:0] scores_69_reg_799;
reg   [11:0] scores_70_reg_804;
reg   [11:0] scores_71_reg_809;
reg   [11:0] scores_72_reg_814;
reg   [11:0] scores_73_reg_819;
wire   [6:0] i_fu_356_p2;
wire    ap_CS_fsm_state3;
wire   [11:0] add_ln703_fu_443_p2;
wire   [0:0] icmp_ln113_fu_350_p2;
wire    grp_tree_scores_fu_44_ap_start;
wire    grp_tree_scores_fu_44_ap_idle;
wire   [3:0] grp_tree_scores_fu_44_x_V_address0;
wire    grp_tree_scores_fu_44_x_V_ce0;
wire   [3:0] grp_tree_scores_fu_44_x_V_address1;
wire    grp_tree_scores_fu_44_x_V_ce1;
wire   [11:0] grp_tree_scores_fu_44_ap_return_0;
wire   [11:0] grp_tree_scores_fu_44_ap_return_1;
wire   [11:0] grp_tree_scores_fu_44_ap_return_2;
wire   [11:0] grp_tree_scores_fu_44_ap_return_3;
wire   [11:0] grp_tree_scores_fu_44_ap_return_4;
wire   [11:0] grp_tree_scores_fu_44_ap_return_5;
wire   [11:0] grp_tree_scores_fu_44_ap_return_6;
wire   [11:0] grp_tree_scores_fu_44_ap_return_7;
wire   [11:0] grp_tree_scores_fu_44_ap_return_8;
wire   [11:0] grp_tree_scores_fu_44_ap_return_9;
wire   [11:0] grp_tree_scores_fu_44_ap_return_10;
wire   [11:0] grp_tree_scores_fu_44_ap_return_11;
wire   [11:0] grp_tree_scores_fu_44_ap_return_12;
wire   [11:0] grp_tree_scores_fu_44_ap_return_13;
wire   [11:0] grp_tree_scores_fu_44_ap_return_14;
wire   [11:0] grp_tree_scores_fu_44_ap_return_15;
wire   [11:0] grp_tree_scores_fu_44_ap_return_16;
wire   [11:0] grp_tree_scores_fu_44_ap_return_17;
wire   [11:0] grp_tree_scores_fu_44_ap_return_18;
wire   [11:0] grp_tree_scores_fu_44_ap_return_19;
wire   [11:0] grp_tree_scores_fu_44_ap_return_20;
wire   [11:0] grp_tree_scores_fu_44_ap_return_21;
wire   [11:0] grp_tree_scores_fu_44_ap_return_22;
wire   [11:0] grp_tree_scores_fu_44_ap_return_23;
wire   [11:0] grp_tree_scores_fu_44_ap_return_24;
wire   [11:0] grp_tree_scores_fu_44_ap_return_25;
wire   [11:0] grp_tree_scores_fu_44_ap_return_26;
wire   [11:0] grp_tree_scores_fu_44_ap_return_27;
wire   [11:0] grp_tree_scores_fu_44_ap_return_28;
wire   [11:0] grp_tree_scores_fu_44_ap_return_29;
wire   [11:0] grp_tree_scores_fu_44_ap_return_30;
wire   [11:0] grp_tree_scores_fu_44_ap_return_31;
wire   [11:0] grp_tree_scores_fu_44_ap_return_32;
wire   [11:0] grp_tree_scores_fu_44_ap_return_33;
wire   [11:0] grp_tree_scores_fu_44_ap_return_34;
wire   [11:0] grp_tree_scores_fu_44_ap_return_35;
wire   [11:0] grp_tree_scores_fu_44_ap_return_36;
wire   [11:0] grp_tree_scores_fu_44_ap_return_37;
wire   [11:0] grp_tree_scores_fu_44_ap_return_38;
wire   [11:0] grp_tree_scores_fu_44_ap_return_39;
wire   [11:0] grp_tree_scores_fu_44_ap_return_40;
wire   [11:0] grp_tree_scores_fu_44_ap_return_41;
wire   [11:0] grp_tree_scores_fu_44_ap_return_42;
wire   [11:0] grp_tree_scores_fu_44_ap_return_43;
wire   [11:0] grp_tree_scores_fu_44_ap_return_44;
wire   [11:0] grp_tree_scores_fu_44_ap_return_45;
wire   [11:0] grp_tree_scores_fu_44_ap_return_46;
wire   [11:0] grp_tree_scores_fu_44_ap_return_47;
wire   [11:0] grp_tree_scores_fu_44_ap_return_48;
wire   [11:0] grp_tree_scores_fu_44_ap_return_49;
wire   [11:0] grp_tree_scores_fu_44_ap_return_50;
wire   [11:0] grp_tree_scores_fu_44_ap_return_51;
wire   [11:0] grp_tree_scores_fu_44_ap_return_52;
wire   [11:0] grp_tree_scores_fu_44_ap_return_53;
wire   [11:0] grp_tree_scores_fu_44_ap_return_54;
wire   [11:0] grp_tree_scores_fu_44_ap_return_55;
wire   [11:0] grp_tree_scores_fu_44_ap_return_56;
wire   [11:0] grp_tree_scores_fu_44_ap_return_57;
wire   [11:0] grp_tree_scores_fu_44_ap_return_58;
wire   [11:0] grp_tree_scores_fu_44_ap_return_59;
wire   [11:0] grp_tree_scores_fu_44_ap_return_60;
wire   [11:0] grp_tree_scores_fu_44_ap_return_61;
wire   [11:0] grp_tree_scores_fu_44_ap_return_62;
wire   [11:0] grp_tree_scores_fu_44_ap_return_63;
wire   [11:0] grp_tree_scores_fu_44_ap_return_64;
wire   [11:0] grp_tree_scores_fu_44_ap_return_65;
wire   [11:0] grp_tree_scores_fu_44_ap_return_66;
wire   [11:0] grp_tree_scores_fu_44_ap_return_67;
wire   [11:0] grp_tree_scores_fu_44_ap_return_68;
wire   [11:0] grp_tree_scores_fu_44_ap_return_69;
wire   [11:0] grp_tree_scores_fu_44_ap_return_70;
wire   [11:0] grp_tree_scores_fu_44_ap_return_71;
wire   [11:0] grp_tree_scores_fu_44_ap_return_72;
wire   [11:0] grp_tree_scores_fu_44_ap_return_73;
wire   [11:0] grp_tree_scores_fu_44_ap_return_74;
reg   [11:0] score_V_0_0_reg_22;
reg   [6:0] i_0_reg_33;
reg    grp_tree_scores_fu_44_ap_start_reg;
wire   [11:0] tmp_fu_362_p77;
reg   [11:0] ap_return_preg;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_tree_scores_fu_44_ap_start_reg = 1'b0;
#0 ap_return_preg = 12'd0;
end

tree_scores grp_tree_scores_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tree_scores_fu_44_ap_start),
    .ap_done(grp_tree_scores_fu_44_ap_done),
    .ap_idle(grp_tree_scores_fu_44_ap_idle),
    .ap_ready(grp_tree_scores_fu_44_ap_ready),
    .x_V_address0(grp_tree_scores_fu_44_x_V_address0),
    .x_V_ce0(grp_tree_scores_fu_44_x_V_ce0),
    .x_V_q0(x_V_q0),
    .x_V_address1(grp_tree_scores_fu_44_x_V_address1),
    .x_V_ce1(grp_tree_scores_fu_44_x_V_ce1),
    .x_V_q1(x_V_q1),
    .ap_return_0(grp_tree_scores_fu_44_ap_return_0),
    .ap_return_1(grp_tree_scores_fu_44_ap_return_1),
    .ap_return_2(grp_tree_scores_fu_44_ap_return_2),
    .ap_return_3(grp_tree_scores_fu_44_ap_return_3),
    .ap_return_4(grp_tree_scores_fu_44_ap_return_4),
    .ap_return_5(grp_tree_scores_fu_44_ap_return_5),
    .ap_return_6(grp_tree_scores_fu_44_ap_return_6),
    .ap_return_7(grp_tree_scores_fu_44_ap_return_7),
    .ap_return_8(grp_tree_scores_fu_44_ap_return_8),
    .ap_return_9(grp_tree_scores_fu_44_ap_return_9),
    .ap_return_10(grp_tree_scores_fu_44_ap_return_10),
    .ap_return_11(grp_tree_scores_fu_44_ap_return_11),
    .ap_return_12(grp_tree_scores_fu_44_ap_return_12),
    .ap_return_13(grp_tree_scores_fu_44_ap_return_13),
    .ap_return_14(grp_tree_scores_fu_44_ap_return_14),
    .ap_return_15(grp_tree_scores_fu_44_ap_return_15),
    .ap_return_16(grp_tree_scores_fu_44_ap_return_16),
    .ap_return_17(grp_tree_scores_fu_44_ap_return_17),
    .ap_return_18(grp_tree_scores_fu_44_ap_return_18),
    .ap_return_19(grp_tree_scores_fu_44_ap_return_19),
    .ap_return_20(grp_tree_scores_fu_44_ap_return_20),
    .ap_return_21(grp_tree_scores_fu_44_ap_return_21),
    .ap_return_22(grp_tree_scores_fu_44_ap_return_22),
    .ap_return_23(grp_tree_scores_fu_44_ap_return_23),
    .ap_return_24(grp_tree_scores_fu_44_ap_return_24),
    .ap_return_25(grp_tree_scores_fu_44_ap_return_25),
    .ap_return_26(grp_tree_scores_fu_44_ap_return_26),
    .ap_return_27(grp_tree_scores_fu_44_ap_return_27),
    .ap_return_28(grp_tree_scores_fu_44_ap_return_28),
    .ap_return_29(grp_tree_scores_fu_44_ap_return_29),
    .ap_return_30(grp_tree_scores_fu_44_ap_return_30),
    .ap_return_31(grp_tree_scores_fu_44_ap_return_31),
    .ap_return_32(grp_tree_scores_fu_44_ap_return_32),
    .ap_return_33(grp_tree_scores_fu_44_ap_return_33),
    .ap_return_34(grp_tree_scores_fu_44_ap_return_34),
    .ap_return_35(grp_tree_scores_fu_44_ap_return_35),
    .ap_return_36(grp_tree_scores_fu_44_ap_return_36),
    .ap_return_37(grp_tree_scores_fu_44_ap_return_37),
    .ap_return_38(grp_tree_scores_fu_44_ap_return_38),
    .ap_return_39(grp_tree_scores_fu_44_ap_return_39),
    .ap_return_40(grp_tree_scores_fu_44_ap_return_40),
    .ap_return_41(grp_tree_scores_fu_44_ap_return_41),
    .ap_return_42(grp_tree_scores_fu_44_ap_return_42),
    .ap_return_43(grp_tree_scores_fu_44_ap_return_43),
    .ap_return_44(grp_tree_scores_fu_44_ap_return_44),
    .ap_return_45(grp_tree_scores_fu_44_ap_return_45),
    .ap_return_46(grp_tree_scores_fu_44_ap_return_46),
    .ap_return_47(grp_tree_scores_fu_44_ap_return_47),
    .ap_return_48(grp_tree_scores_fu_44_ap_return_48),
    .ap_return_49(grp_tree_scores_fu_44_ap_return_49),
    .ap_return_50(grp_tree_scores_fu_44_ap_return_50),
    .ap_return_51(grp_tree_scores_fu_44_ap_return_51),
    .ap_return_52(grp_tree_scores_fu_44_ap_return_52),
    .ap_return_53(grp_tree_scores_fu_44_ap_return_53),
    .ap_return_54(grp_tree_scores_fu_44_ap_return_54),
    .ap_return_55(grp_tree_scores_fu_44_ap_return_55),
    .ap_return_56(grp_tree_scores_fu_44_ap_return_56),
    .ap_return_57(grp_tree_scores_fu_44_ap_return_57),
    .ap_return_58(grp_tree_scores_fu_44_ap_return_58),
    .ap_return_59(grp_tree_scores_fu_44_ap_return_59),
    .ap_return_60(grp_tree_scores_fu_44_ap_return_60),
    .ap_return_61(grp_tree_scores_fu_44_ap_return_61),
    .ap_return_62(grp_tree_scores_fu_44_ap_return_62),
    .ap_return_63(grp_tree_scores_fu_44_ap_return_63),
    .ap_return_64(grp_tree_scores_fu_44_ap_return_64),
    .ap_return_65(grp_tree_scores_fu_44_ap_return_65),
    .ap_return_66(grp_tree_scores_fu_44_ap_return_66),
    .ap_return_67(grp_tree_scores_fu_44_ap_return_67),
    .ap_return_68(grp_tree_scores_fu_44_ap_return_68),
    .ap_return_69(grp_tree_scores_fu_44_ap_return_69),
    .ap_return_70(grp_tree_scores_fu_44_ap_return_70),
    .ap_return_71(grp_tree_scores_fu_44_ap_return_71),
    .ap_return_72(grp_tree_scores_fu_44_ap_return_72),
    .ap_return_73(grp_tree_scores_fu_44_ap_return_73),
    .ap_return_74(grp_tree_scores_fu_44_ap_return_74)
);

my_prj_acceleratocud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 12 ),
    .din4_WIDTH( 12 ),
    .din5_WIDTH( 12 ),
    .din6_WIDTH( 12 ),
    .din7_WIDTH( 12 ),
    .din8_WIDTH( 12 ),
    .din9_WIDTH( 12 ),
    .din10_WIDTH( 12 ),
    .din11_WIDTH( 12 ),
    .din12_WIDTH( 12 ),
    .din13_WIDTH( 12 ),
    .din14_WIDTH( 12 ),
    .din15_WIDTH( 12 ),
    .din16_WIDTH( 12 ),
    .din17_WIDTH( 12 ),
    .din18_WIDTH( 12 ),
    .din19_WIDTH( 12 ),
    .din20_WIDTH( 12 ),
    .din21_WIDTH( 12 ),
    .din22_WIDTH( 12 ),
    .din23_WIDTH( 12 ),
    .din24_WIDTH( 12 ),
    .din25_WIDTH( 12 ),
    .din26_WIDTH( 12 ),
    .din27_WIDTH( 12 ),
    .din28_WIDTH( 12 ),
    .din29_WIDTH( 12 ),
    .din30_WIDTH( 12 ),
    .din31_WIDTH( 12 ),
    .din32_WIDTH( 12 ),
    .din33_WIDTH( 12 ),
    .din34_WIDTH( 12 ),
    .din35_WIDTH( 12 ),
    .din36_WIDTH( 12 ),
    .din37_WIDTH( 12 ),
    .din38_WIDTH( 12 ),
    .din39_WIDTH( 12 ),
    .din40_WIDTH( 12 ),
    .din41_WIDTH( 12 ),
    .din42_WIDTH( 12 ),
    .din43_WIDTH( 12 ),
    .din44_WIDTH( 12 ),
    .din45_WIDTH( 12 ),
    .din46_WIDTH( 12 ),
    .din47_WIDTH( 12 ),
    .din48_WIDTH( 12 ),
    .din49_WIDTH( 12 ),
    .din50_WIDTH( 12 ),
    .din51_WIDTH( 12 ),
    .din52_WIDTH( 12 ),
    .din53_WIDTH( 12 ),
    .din54_WIDTH( 12 ),
    .din55_WIDTH( 12 ),
    .din56_WIDTH( 12 ),
    .din57_WIDTH( 12 ),
    .din58_WIDTH( 12 ),
    .din59_WIDTH( 12 ),
    .din60_WIDTH( 12 ),
    .din61_WIDTH( 12 ),
    .din62_WIDTH( 12 ),
    .din63_WIDTH( 12 ),
    .din64_WIDTH( 12 ),
    .din65_WIDTH( 12 ),
    .din66_WIDTH( 12 ),
    .din67_WIDTH( 12 ),
    .din68_WIDTH( 12 ),
    .din69_WIDTH( 12 ),
    .din70_WIDTH( 12 ),
    .din71_WIDTH( 12 ),
    .din72_WIDTH( 12 ),
    .din73_WIDTH( 12 ),
    .din74_WIDTH( 12 ),
    .din75_WIDTH( 7 ),
    .dout_WIDTH( 12 ))
my_prj_acceleratocud_U188(
    .din0(scores_reg_449),
    .din1(scores_1_reg_454),
    .din2(scores_2_reg_459),
    .din3(scores_3_reg_464),
    .din4(scores_4_reg_469),
    .din5(scores_5_reg_474),
    .din6(scores_6_reg_479),
    .din7(scores_7_reg_484),
    .din8(scores_8_reg_489),
    .din9(scores_9_reg_494),
    .din10(scores_s_reg_499),
    .din11(scores_10_reg_504),
    .din12(scores_11_reg_509),
    .din13(scores_12_reg_514),
    .din14(scores_13_reg_519),
    .din15(scores_14_reg_524),
    .din16(scores_15_reg_529),
    .din17(scores_16_reg_534),
    .din18(scores_17_reg_539),
    .din19(scores_18_reg_544),
    .din20(scores_19_reg_549),
    .din21(scores_20_reg_554),
    .din22(scores_21_reg_559),
    .din23(scores_22_reg_564),
    .din24(scores_23_reg_569),
    .din25(scores_24_reg_574),
    .din26(scores_25_reg_579),
    .din27(scores_26_reg_584),
    .din28(scores_27_reg_589),
    .din29(scores_28_reg_594),
    .din30(scores_29_reg_599),
    .din31(scores_30_reg_604),
    .din32(scores_31_reg_609),
    .din33(scores_32_reg_614),
    .din34(scores_33_reg_619),
    .din35(scores_34_reg_624),
    .din36(scores_35_reg_629),
    .din37(scores_36_reg_634),
    .din38(scores_37_reg_639),
    .din39(scores_38_reg_644),
    .din40(scores_39_reg_649),
    .din41(scores_40_reg_654),
    .din42(scores_41_reg_659),
    .din43(scores_42_reg_664),
    .din44(scores_43_reg_669),
    .din45(scores_44_reg_674),
    .din46(scores_45_reg_679),
    .din47(scores_46_reg_684),
    .din48(scores_47_reg_689),
    .din49(scores_48_reg_694),
    .din50(scores_49_reg_699),
    .din51(scores_50_reg_704),
    .din52(scores_51_reg_709),
    .din53(scores_52_reg_714),
    .din54(scores_53_reg_719),
    .din55(scores_54_reg_724),
    .din56(scores_55_reg_729),
    .din57(scores_56_reg_734),
    .din58(scores_57_reg_739),
    .din59(scores_58_reg_744),
    .din60(scores_59_reg_749),
    .din61(scores_60_reg_754),
    .din62(scores_61_reg_759),
    .din63(scores_62_reg_764),
    .din64(scores_63_reg_769),
    .din65(scores_64_reg_774),
    .din66(scores_65_reg_779),
    .din67(scores_66_reg_784),
    .din68(scores_67_reg_789),
    .din69(scores_68_reg_794),
    .din70(scores_69_reg_799),
    .din71(scores_70_reg_804),
    .din72(scores_71_reg_809),
    .din73(scores_72_reg_814),
    .din74(scores_73_reg_819),
    .din75(i_0_reg_33),
    .dout(tmp_fu_362_p77)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 12'd0;
    end else begin
        if (((icmp_ln113_fu_350_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_return_preg <= score_V_0_0_reg_22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tree_scores_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_tree_scores_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_tree_scores_fu_44_ap_ready == 1'b1)) begin
            grp_tree_scores_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln113_fu_350_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_reg_33 <= i_fu_356_p2;
    end else if (((grp_tree_scores_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_0_reg_33 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln113_fu_350_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        score_V_0_0_reg_22 <= add_ln703_fu_443_p2;
    end else if (((grp_tree_scores_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        score_V_0_0_reg_22 <= 12'd361;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tree_scores_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        scores_10_reg_504 <= grp_tree_scores_fu_44_ap_return_11;
        scores_11_reg_509 <= grp_tree_scores_fu_44_ap_return_12;
        scores_12_reg_514 <= grp_tree_scores_fu_44_ap_return_13;
        scores_13_reg_519 <= grp_tree_scores_fu_44_ap_return_14;
        scores_14_reg_524 <= grp_tree_scores_fu_44_ap_return_15;
        scores_15_reg_529 <= grp_tree_scores_fu_44_ap_return_16;
        scores_16_reg_534 <= grp_tree_scores_fu_44_ap_return_17;
        scores_17_reg_539 <= grp_tree_scores_fu_44_ap_return_18;
        scores_18_reg_544 <= grp_tree_scores_fu_44_ap_return_19;
        scores_19_reg_549 <= grp_tree_scores_fu_44_ap_return_20;
        scores_1_reg_454 <= grp_tree_scores_fu_44_ap_return_1;
        scores_20_reg_554 <= grp_tree_scores_fu_44_ap_return_21;
        scores_21_reg_559 <= grp_tree_scores_fu_44_ap_return_22;
        scores_22_reg_564 <= grp_tree_scores_fu_44_ap_return_23;
        scores_23_reg_569 <= grp_tree_scores_fu_44_ap_return_24;
        scores_24_reg_574 <= grp_tree_scores_fu_44_ap_return_25;
        scores_25_reg_579 <= grp_tree_scores_fu_44_ap_return_26;
        scores_26_reg_584 <= grp_tree_scores_fu_44_ap_return_27;
        scores_27_reg_589 <= grp_tree_scores_fu_44_ap_return_28;
        scores_28_reg_594 <= grp_tree_scores_fu_44_ap_return_29;
        scores_29_reg_599 <= grp_tree_scores_fu_44_ap_return_30;
        scores_2_reg_459 <= grp_tree_scores_fu_44_ap_return_2;
        scores_30_reg_604 <= grp_tree_scores_fu_44_ap_return_31;
        scores_31_reg_609 <= grp_tree_scores_fu_44_ap_return_32;
        scores_32_reg_614 <= grp_tree_scores_fu_44_ap_return_33;
        scores_33_reg_619 <= grp_tree_scores_fu_44_ap_return_34;
        scores_34_reg_624 <= grp_tree_scores_fu_44_ap_return_35;
        scores_35_reg_629 <= grp_tree_scores_fu_44_ap_return_36;
        scores_36_reg_634 <= grp_tree_scores_fu_44_ap_return_37;
        scores_37_reg_639 <= grp_tree_scores_fu_44_ap_return_38;
        scores_38_reg_644 <= grp_tree_scores_fu_44_ap_return_39;
        scores_39_reg_649 <= grp_tree_scores_fu_44_ap_return_40;
        scores_3_reg_464 <= grp_tree_scores_fu_44_ap_return_3;
        scores_40_reg_654 <= grp_tree_scores_fu_44_ap_return_41;
        scores_41_reg_659 <= grp_tree_scores_fu_44_ap_return_42;
        scores_42_reg_664 <= grp_tree_scores_fu_44_ap_return_43;
        scores_43_reg_669 <= grp_tree_scores_fu_44_ap_return_44;
        scores_44_reg_674 <= grp_tree_scores_fu_44_ap_return_45;
        scores_45_reg_679 <= grp_tree_scores_fu_44_ap_return_46;
        scores_46_reg_684 <= grp_tree_scores_fu_44_ap_return_47;
        scores_47_reg_689 <= grp_tree_scores_fu_44_ap_return_48;
        scores_48_reg_694 <= grp_tree_scores_fu_44_ap_return_49;
        scores_49_reg_699 <= grp_tree_scores_fu_44_ap_return_50;
        scores_4_reg_469 <= grp_tree_scores_fu_44_ap_return_4;
        scores_50_reg_704 <= grp_tree_scores_fu_44_ap_return_51;
        scores_51_reg_709 <= grp_tree_scores_fu_44_ap_return_52;
        scores_52_reg_714 <= grp_tree_scores_fu_44_ap_return_53;
        scores_53_reg_719 <= grp_tree_scores_fu_44_ap_return_54;
        scores_54_reg_724 <= grp_tree_scores_fu_44_ap_return_55;
        scores_55_reg_729 <= grp_tree_scores_fu_44_ap_return_56;
        scores_56_reg_734 <= grp_tree_scores_fu_44_ap_return_57;
        scores_57_reg_739 <= grp_tree_scores_fu_44_ap_return_58;
        scores_58_reg_744 <= grp_tree_scores_fu_44_ap_return_59;
        scores_59_reg_749 <= grp_tree_scores_fu_44_ap_return_60;
        scores_5_reg_474 <= grp_tree_scores_fu_44_ap_return_5;
        scores_60_reg_754 <= grp_tree_scores_fu_44_ap_return_61;
        scores_61_reg_759 <= grp_tree_scores_fu_44_ap_return_62;
        scores_62_reg_764 <= grp_tree_scores_fu_44_ap_return_63;
        scores_63_reg_769 <= grp_tree_scores_fu_44_ap_return_64;
        scores_64_reg_774 <= grp_tree_scores_fu_44_ap_return_65;
        scores_65_reg_779 <= grp_tree_scores_fu_44_ap_return_66;
        scores_66_reg_784 <= grp_tree_scores_fu_44_ap_return_67;
        scores_67_reg_789 <= grp_tree_scores_fu_44_ap_return_68;
        scores_68_reg_794 <= grp_tree_scores_fu_44_ap_return_69;
        scores_69_reg_799 <= grp_tree_scores_fu_44_ap_return_70;
        scores_6_reg_479 <= grp_tree_scores_fu_44_ap_return_6;
        scores_70_reg_804 <= grp_tree_scores_fu_44_ap_return_71;
        scores_71_reg_809 <= grp_tree_scores_fu_44_ap_return_72;
        scores_72_reg_814 <= grp_tree_scores_fu_44_ap_return_73;
        scores_73_reg_819 <= grp_tree_scores_fu_44_ap_return_74;
        scores_7_reg_484 <= grp_tree_scores_fu_44_ap_return_7;
        scores_8_reg_489 <= grp_tree_scores_fu_44_ap_return_8;
        scores_9_reg_494 <= grp_tree_scores_fu_44_ap_return_9;
        scores_reg_449 <= grp_tree_scores_fu_44_ap_return_0;
        scores_s_reg_499 <= grp_tree_scores_fu_44_ap_return_10;
    end
end

always @ (*) begin
    if ((((icmp_ln113_fu_350_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln113_fu_350_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln113_fu_350_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_return = score_V_0_0_reg_22;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_tree_scores_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln113_fu_350_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln703_fu_443_p2 = (tmp_fu_362_p77 + score_V_0_0_reg_22);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign grp_tree_scores_fu_44_ap_start = grp_tree_scores_fu_44_ap_start_reg;

assign i_fu_356_p2 = (i_0_reg_33 + 7'd1);

assign icmp_ln113_fu_350_p2 = ((i_0_reg_33 == 7'd75) ? 1'b1 : 1'b0);

assign x_V_address0 = grp_tree_scores_fu_44_x_V_address0;

assign x_V_address1 = grp_tree_scores_fu_44_x_V_address1;

assign x_V_ce0 = grp_tree_scores_fu_44_x_V_ce0;

assign x_V_ce1 = grp_tree_scores_fu_44_x_V_ce1;

endmodule //decision_function_75
