// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _decision_function_79_HH_
#define _decision_function_79_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "my_prj_acceleratobkb_x0.h"

namespace ap_rtl {

struct decision_function_79 : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > x_V_address0;
    sc_out< sc_logic > x_V_ce0;
    sc_in< sc_lv<12> > x_V_q0;
    sc_out< sc_lv<4> > x_V_address1;
    sc_out< sc_logic > x_V_ce1;
    sc_in< sc_lv<12> > x_V_q1;
    sc_out< sc_lv<12> > ap_return;
    sc_signal< sc_lv<12> > ap_var_for_const0;
    sc_signal< sc_lv<12> > ap_var_for_const1;
    sc_signal< sc_lv<12> > ap_var_for_const2;
    sc_signal< sc_lv<12> > ap_var_for_const3;
    sc_signal< sc_lv<12> > ap_var_for_const4;
    sc_signal< sc_lv<12> > ap_var_for_const5;
    sc_signal< sc_lv<12> > ap_var_for_const6;
    sc_signal< sc_lv<12> > ap_var_for_const7;


    // Module declarations
    decision_function_79(sc_module_name name);
    SC_HAS_PROCESS(decision_function_79);

    ~decision_function_79();

    sc_trace_file* mVcdFile;

    my_prj_acceleratobkb_x0<1,1,12,12,12,12,12,12,12,12,3,12>* my_prj_acceleratobkb_x0_U43;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage1;
    sc_signal< bool > ap_block_state2_pp0_stage1_iter0;
    sc_signal< bool > ap_block_state4_pp0_stage1_iter1;
    sc_signal< bool > ap_block_pp0_stage1_11001;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<1> > icmp_ln1497_fu_107_p2;
    sc_signal< sc_lv<1> > icmp_ln1497_reg_319;
    sc_signal< sc_lv<1> > icmp_ln1497_1_fu_113_p2;
    sc_signal< sc_lv<1> > icmp_ln1497_1_reg_329;
    sc_signal< sc_lv<1> > icmp_ln1497_9_fu_119_p2;
    sc_signal< sc_lv<1> > icmp_ln1497_9_reg_345;
    sc_signal< sc_lv<1> > icmp_ln1497_12_fu_125_p2;
    sc_signal< sc_lv<1> > icmp_ln1497_12_reg_350;
    sc_signal< sc_lv<1> > icmp_ln1497_2_fu_131_p2;
    sc_signal< sc_lv<1> > icmp_ln1497_2_reg_355;
    sc_signal< sc_lv<1> > icmp_ln1497_5_fu_137_p2;
    sc_signal< sc_lv<1> > icmp_ln1497_5_reg_360;
    sc_signal< sc_lv<1> > icmp_ln1497_8_fu_143_p2;
    sc_signal< sc_lv<1> > icmp_ln1497_8_reg_365;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0_reg;
    sc_signal< bool > ap_block_pp0_stage1_subdone;
    sc_signal< bool > ap_block_pp0_stage1;
    sc_signal< sc_lv<1> > and_ln73_fu_149_p2;
    sc_signal< sc_lv<1> > xor_ln75_fu_158_p2;
    sc_signal< sc_lv<1> > and_ln73_68_fu_163_p2;
    sc_signal< sc_lv<1> > xor_ln75_21_fu_173_p2;
    sc_signal< sc_lv<1> > and_ln73_70_fu_178_p2;
    sc_signal< sc_lv<1> > and_ln73_72_fu_193_p2;
    sc_signal< sc_lv<1> > xor_ln75_22_fu_188_p2;
    sc_signal< sc_lv<1> > and_ln73_69_fu_168_p2;
    sc_signal< sc_lv<1> > and_ln73_71_fu_183_p2;
    sc_signal< sc_lv<1> > or_ln88_32_fu_215_p2;
    sc_signal< sc_lv<1> > and_ln73_73_fu_198_p2;
    sc_signal< sc_lv<1> > and_ln73_67_fu_153_p2;
    sc_signal< sc_lv<1> > xor_ln89_fu_226_p2;
    sc_signal< sc_lv<2> > zext_ln89_fu_232_p1;
    sc_signal< sc_lv<1> > or_ln88_fu_204_p2;
    sc_signal< sc_lv<2> > select_ln89_fu_236_p3;
    sc_signal< sc_lv<2> > select_ln89_51_fu_244_p3;
    sc_signal< sc_lv<3> > zext_ln89_7_fu_252_p1;
    sc_signal< sc_lv<1> > or_ln88_31_fu_210_p2;
    sc_signal< sc_lv<3> > select_ln89_52_fu_256_p3;
    sc_signal< sc_lv<3> > select_ln89_53_fu_263_p3;
    sc_signal< sc_lv<1> > or_ln88_33_fu_220_p2;
    sc_signal< sc_lv<3> > select_ln89_54_fu_271_p3;
    sc_signal< sc_lv<3> > tmp_fu_287_p9;
    sc_signal< sc_lv<12> > tmp_fu_287_p10;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_idle_pp0_1to1;
    sc_signal< sc_logic > ap_idle_pp0_0to0;
    sc_signal< sc_logic > ap_reset_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_pp0_stage0;
    static const sc_lv<2> ap_ST_fsm_pp0_stage1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_4;
    static const sc_lv<64> ap_const_lv64_9;
    static const sc_lv<12> ap_const_lv12_C01;
    static const sc_lv<12> ap_const_lv12_1;
    static const sc_lv<12> ap_const_lv12_381;
    static const sc_lv<12> ap_const_lv12_E81;
    static const sc_lv<12> ap_const_lv12_401;
    static const sc_lv<12> ap_const_lv12_B81;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_6;
    static const sc_lv<3> ap_const_lv3_7;
    static const sc_lv<12> ap_const_lv12_FD7;
    static const sc_lv<12> ap_const_lv12_1A;
    static const sc_lv<12> ap_const_lv12_FE9;
    static const sc_lv<12> ap_const_lv12_F87;
    static const sc_lv<12> ap_const_lv12_FE4;
    static const sc_lv<12> ap_const_lv12_FE3;
    static const sc_lv<12> ap_const_lv12_14;
    static const sc_lv<12> ap_const_lv12_FDE;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const4();
    void thread_ap_var_for_const5();
    void thread_ap_var_for_const6();
    void thread_ap_var_for_const7();
    void thread_ap_clk_no_reset_();
    void thread_and_ln73_67_fu_153_p2();
    void thread_and_ln73_68_fu_163_p2();
    void thread_and_ln73_69_fu_168_p2();
    void thread_and_ln73_70_fu_178_p2();
    void thread_and_ln73_71_fu_183_p2();
    void thread_and_ln73_72_fu_193_p2();
    void thread_and_ln73_73_fu_198_p2();
    void thread_and_ln73_fu_149_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_pp0_stage1();
    void thread_ap_block_pp0_stage1_11001();
    void thread_ap_block_pp0_stage1_subdone();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage1_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_pp0_stage1_iter1();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_enable_reg_pp0_iter0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_idle_pp0_0to0();
    void thread_ap_idle_pp0_1to1();
    void thread_ap_ready();
    void thread_ap_reset_idle_pp0();
    void thread_ap_return();
    void thread_icmp_ln1497_12_fu_125_p2();
    void thread_icmp_ln1497_1_fu_113_p2();
    void thread_icmp_ln1497_2_fu_131_p2();
    void thread_icmp_ln1497_5_fu_137_p2();
    void thread_icmp_ln1497_8_fu_143_p2();
    void thread_icmp_ln1497_9_fu_119_p2();
    void thread_icmp_ln1497_fu_107_p2();
    void thread_or_ln88_31_fu_210_p2();
    void thread_or_ln88_32_fu_215_p2();
    void thread_or_ln88_33_fu_220_p2();
    void thread_or_ln88_fu_204_p2();
    void thread_select_ln89_51_fu_244_p3();
    void thread_select_ln89_52_fu_256_p3();
    void thread_select_ln89_53_fu_263_p3();
    void thread_select_ln89_54_fu_271_p3();
    void thread_select_ln89_fu_236_p3();
    void thread_tmp_fu_287_p9();
    void thread_x_V_address0();
    void thread_x_V_address1();
    void thread_x_V_ce0();
    void thread_x_V_ce1();
    void thread_xor_ln75_21_fu_173_p2();
    void thread_xor_ln75_22_fu_188_p2();
    void thread_xor_ln75_fu_158_p2();
    void thread_xor_ln89_fu_226_p2();
    void thread_zext_ln89_7_fu_252_p1();
    void thread_zext_ln89_fu_232_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
